<?php
defined('BASEPATH') or exit('No direct script access allowed');

class Migrate extends CI_Model
{

	public function __construct()
	{
		parent::__construct();
	}

	// Function to run migration for creating user table
	public function create_user_table()
	{
		$query = "
        CREATE TABLE IF NOT EXISTS skpi.user (
            id_user BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            nama VARCHAR(100) NOT NULL,
            alamat TEXT
        )";

		if (!$this->db->query($query)) {
			log_message('error', 'Error creating user table: ' . $this->db->last_query());
			return false;
		}
		return true;
	}

	// Function to run migration for creating auth table
	public function create_auth_table()
	{
		$query = "
        CREATE TABLE IF NOT EXISTS skpi.auth (
            id_auth BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            id_user BIGINT NOT NULL,
            email VARCHAR(255) UNIQUE NOT NULL,
            password VARCHAR(255) NOT NULL,
            role VARCHAR(50) NOT NULL,
            FOREIGN KEY (id_user) REFERENCES skpi.user(id_user)
        )";

		if (!$this->db->query($query)) {
			log_message('error', 'Error creating auth table: ' . $this->db->last_query());
			return false;
		}
		return true;
	}
	public function insert_user_table()
	{
		$query = "INSERT INTO skpi.user (nama, alamat) VALUES ( 'Mahasiswa Universitas Alma Ata', 'Sekitaran kampus pokoknya' ), ( 'Dosen UAA', 'Ya masih di sekitaran Jogja' ), ( 'Admin Kemahasiswaan', 'masih sama disekitaran jogja' ), ( 'Admin Akademik', 'masih sama juga disekitaran jogja' ), ( 'Admin Operator', 'Dimana saja bisa')";

		if (!$this->db->query($query)) {
			log_message('error', 'Error insert user table: ' . $this->db->last_query());
			return false;
		}
		return true;
	}
	public function insert_auth_table()
	{
		$data = [
			[
				'id_user' => 1,
				'email' => 'mahasiswa@almaata.ac.id',
				'password' => '$argon2id$v=19$m=16,t=2,p=1$T1BhODhZZTV2WTBtSVJEMQ$PyVa1vL+WCz8zQA5/RTRwQ',
				'role' => 'mahasiswa'
			],
			[
				'id_user' => 2,
				'email' => 'dosen@almaata.ac.id',
				'password' => '$argon2id$v=19$m=16,t=2,p=1$T1BhODhZZTV2WTBtSVJEMQ$PyVa1vL+WCz8zQA5/RTRwQ',
				'role' => 'dosen'
			],
			[
				'id_user' => 3,
				'email' => 'kemahasiswaan@almaata.ac.id',
				'password' => '$argon2id$v=19$m=16,t=2,p=1$T1BhODhZZTV2WTBtSVJEMQ$PyVa1vL+WCz8zQA5/RTRwQ',
				'role' => 'kemahasiswaan'
			],
			[
				'id_user' => 4,
				'email' => 'akademik@almaata.ac.id',
				'password' => '$argon2id$v=19$m=16,t=2,p=1$T1BhODhZZTV2WTBtSVJEMQ$PyVa1vL+WCz8zQA5/RTRwQ',
				'role' => 'akademik'
			],
			[
				'id_user' => 5,
				'email' => 'administrator@almaata.ac.id',
				'password' => '$argon2id$v=19$m=16,t=2,p=1$T1BhODhZZTV2WTBtSVJEMQ$PyVa1vL+WCz8zQA5/RTRwQ',
				'role' => 'admin'
			]
		];

		// Insert ke dalam database
		foreach ($data as $row) {
			$this->db->insert('auth', $row);
		}

		return true;
	}

	// Function to drop user table
	public function drop_user_table()
	{
		$this->db->query('DROP TABLE IF EXISTS skpi.user');
	}

	// Function to drop auth table
	public function drop_auth_table()
	{
		$this->db->query('DROP TABLE IF EXISTS skpi.auth');
	}

	// Function to show all data from user table
	public function show_user_table()
	{
		$query = $this->db->get('user');
		return $query->result();
	}

	// Function to show all data from auth table
	public function show_auth_table()
	{
		$query = $this->db->get('auth');
		return $query->result();
	}
}
